name: coawst
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - intake-xarray
  - fsspec 
  - s3fs
  - xarray 
  - cf_xarray
  - zarr
  - xoak
  - fastparquet
  - dask 
  - datashader
  - geoviews
  - hvplot
  - panel
